name: Publica a documentação automaticamente no github-pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PhpDocumentor
      uses: gpupo/actions-phpDocumentor@1.0

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        CLEAN: true
